[package]
name = "browser"
version = "0.0.1"
authors = ["Nate Yazdani <nyazdani@cs.washington.edu>", "Matt Brubeck <mbrubeck@limpet.net>"]
edition = "2018"

[[bin]]
name = "browser"
path = "src/main.rs"

[dependencies]
getopts = "0.2.19"
itertools = "0.8"
image = "0.14"
